### ISSUE TITLE
ControlNet not displayed

### ISSUE THREAD

**Issue by gabrieltaliano** [ashleykleynhans/a1111-docker#7]
Hi, I deployed today in Runpod (1 x RTX A6000, 9 vCPU 50 GB RAM), but I cannot find controlNet. And I have the message: "ControlNet not found. Please install it :)" in the Deforum section.

version: [v1.9.3](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0)  •  python: 3.10.12  •  torch: 2.1.2+cu118  •  xformers: 0.0.23.post1+cu118  •  gradio: 3.41.2  •  checkpoint: [e3edb8a26f](https://google.com/search?q=e3edb8a26f44dfddc124129004b5ded3378be974b8d3bf82f43b9660d416d3d1)

Tried to reinstall the controlNet extension, update and restart the pod, but still nothing.

Also tried running pip install -r requirements.txt in the controlNet extension directory.

**Comment by ashleykleynhans** [comment]
Log a bug under Deforum extension on GitHub. This is just a docker image, I
am not the developer of Deforum and ControlNet is definitely installed.

**Comment by gabrieltaliano** [comment]
I deployed it again but from scratch and it's working. The previous deploy was with a Network Volume attached. Probably some old config was overlapping.

Thanks anyway!
And thanks for your work :)
