### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Goosebumps1206** [ashleykleynhans/a1111-docker#8]
NotImplementedError: No operator found for memory_efficient_attention_forward with inputs: query : shape=(1, 12288, 1, 512) (torch.float16) key : shape=(1, 12288, 1, 512) (torch.float16) value : shape=(1, 12288, 1, 512) (torch.float16) attn_bias : <class 'NoneType'> p : 0.0 decoderF is not supported because: max(query.shape[-1] != value.shape[-1]) > 128 xFormers wasn't build with CUDA support attn_bias type is <class 'NoneType'> operator wasn't built - see python -m xformers.info for more info flshattF@0.0.0 is not supported because: max(query.shape[-1] != value.shape[-1]) > 256 xFormers wasn't build with CUDA support operator wasn't built - see python -m xformers.info for more info tritonflashattF is not supported because: max(query.shape[-1] != value.shape[-1]) > 128 xFormers wasn't build with CUDA support operator wasn't built - see python -m xformers.info for more info triton is not available Only work on pre-MLIR triton for now cutlassF is not supported because: xFormers wasn't build with CUDA support operator wasn't built - see python -m xformers.info for more info smallkF is not supported because: max(query.shape[-1] != value.shape[-1]) > 32 xFormers wasn't build with CUDA support dtype=torch.float16 (supported: {torch.float32}) operator wasn't built - see python -m xformers.info for more info unsupported embed per head: 512
Time taken: 0.2 sec.

**Comment by ashleykleynhans** [comment]
What were you doing when you got this error?

**Comment by Goosebumps1206** [comment]
Trying to run img2img using batch

**Comment by ashleykleynhans** [comment]
Please share your settings, its impossible to know what the issue is without the exact settings you are using.

**Comment by Goosebumps1206** [comment]
Hi Ashley, how do I share the settings?

**Comment by Goosebumps1206** [comment]
I have replicated the error again this morning. Attache are 2 x screenshots of the UI if that helps. 
![Screenshot 2024-07-28 at 09 07 31](https://github.com/user-attachments/assets/50d498c4-ced0-431c-a6d3-b562c6594363)
![Screenshot 2024-07-28 at 09 07 52](https://github.com/user-attachments/assets/2e956541-df51-4e02-90c4-4d57046a095d)

**Comment by ashleykleynhans** [comment]
Seems like a bug in new version of A1111 1.10.0, log a bug in their GitHub, I am not the developer of A1111.
https://github.com/AUTOMATIC1111/stable-diffusion-webui
